eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka

spring:
  application:
    name: sleuth_provider
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:6001
server:
  port: 7001