server:
  port: 3001
spring:
  application:
    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: user
#          uri: http://localhost:6001
#          predicates:
#            - Path=/user/**