eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:5000/eureka
spring:
  application:
    name: config_server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
server:
  port: 6001